security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: phone
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        facade:
            #для всех урлов которые начинаются на /, кроме api
            pattern: ^/profile/
            lazy: true
            provider: app_user_provider
            stateless: true
            custom_authenticators:
                - App\Security\UserAuthenticator
        api:
            #для всех урлов которые начинаются на /api, кроме restore,... и методов из supports в аутентификаторе
            pattern: ^/api/(?!(user\/(restore|confirmation))|doc|sms|dial|specialist/\d+|filter|system)
            lazy: true
            provider: app_user_provider
            stateless: true
            custom_authenticators:
                - App\Security\ApiKeyAuthenticator
        optional:
            #для всех урлов, опциональная авторизация, либо есть, либо нет
            pattern: ^/
            lazy: true
            provider: app_user_provider
            stateless: true
            custom_authenticators:
                - App\Security\OptionalAuthenticator
        main:
            lazy: true
            provider: app_user_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
